import type { Theme } from '../types'

export const THEMES: Record<string, Theme> = {
  default: {
    id: 'default',
    name: 'Crimson Classic',
    emoji: '🎓',
    primaryColor: '#A51C30',
    accentColor: '#C9A84C',
    backgroundColor: '#F9F6F0',
    headerBg: 'linear-gradient(135deg, #A51C30 0%, #6d1020 100%)',
    headerText: '#FFFFFF',
    sectionBorderColor: '#A51C30',
    sectionHeaderBg: '#fdf2f4',
    sectionHeaderText: '#A51C30',
    bodyText: '#2d2d2d',
    decorativeClass: 'decor-default',
  },
  halloween: {
    id: 'halloween',
    name: 'Halloween',
    emoji: '🎃',
    primaryColor: '#E07B39',
    accentColor: '#F5A623',
    backgroundColor: '#1A1A1A',
    headerBg: 'linear-gradient(135deg, #2D1B00 0%, #1A1A1A 100%)',
    headerText: '#F5A623',
    sectionBorderColor: '#E07B39',
    sectionHeaderBg: '#2D1B00',
    sectionHeaderText: '#F5A623',
    bodyText: '#F0E6D3',
    decorativeClass: 'decor-halloween',
  },
  thanksgiving: {
    id: 'thanksgiving',
    name: 'Thanksgiving',
    emoji: '🍂',
    primaryColor: '#C4622D',
    accentColor: '#D4A017',
    backgroundColor: '#FDF6EE',
    headerBg: 'linear-gradient(135deg, #C4622D 0%, #8B3A1A 100%)',
    headerText: '#FFF8F0',
    sectionBorderColor: '#C4622D',
    sectionHeaderBg: '#FEF0E3',
    sectionHeaderText: '#8B3A1A',
    bodyText: '#3D2314',
    decorativeClass: 'decor-thanksgiving',
  },
  holiday: {
    id: 'holiday',
    name: 'Holiday',
    emoji: '🎄',
    primaryColor: '#1B5E20',
    accentColor: '#FFD700',
    backgroundColor: '#F0FFF0',
    headerBg: 'linear-gradient(135deg, #1B5E20 0%, #B71C1C 100%)',
    headerText: '#FFD700',
    sectionBorderColor: '#1B5E20',
    sectionHeaderBg: '#E8F5E9',
    sectionHeaderText: '#1B5E20',
    bodyText: '#1A2E1A',
    decorativeClass: 'decor-holiday',
  },
  valentines: {
    id: 'valentines',
    name: "Valentine's Day",
    emoji: '💕',
    primaryColor: '#C2185B',
    accentColor: '#E91E63',
    backgroundColor: '#FFF0F5',
    headerBg: 'linear-gradient(135deg, #C2185B 0%, #880E4F 100%)',
    headerText: '#FFE4EE',
    sectionBorderColor: '#C2185B',
    sectionHeaderBg: '#FCE4EC',
    sectionHeaderText: '#880E4F',
    bodyText: '#2d0a1e',
    decorativeClass: 'decor-valentines',
  },
  spring: {
    id: 'spring',
    name: 'Spring',
    emoji: '🌸',
    primaryColor: '#7B1FA2',
    accentColor: '#4CAF50',
    backgroundColor: '#F8F4FF',
    headerBg: 'linear-gradient(135deg, #7B1FA2 0%, #4CAF50 100%)',
    headerText: '#FFFFFF',
    sectionBorderColor: '#7B1FA2',
    sectionHeaderBg: '#F3E5F5',
    sectionHeaderText: '#6A1B9A',
    bodyText: '#2d1a3a',
    decorativeClass: 'decor-spring',
  },
  summer: {
    id: 'summer',
    name: 'Summer',
    emoji: '☀️',
    primaryColor: '#0277BD',
    accentColor: '#FDD835',
    backgroundColor: '#F0F8FF',
    headerBg: 'linear-gradient(135deg, #0277BD 0%, #01579B 100%)',
    headerText: '#FDD835',
    sectionBorderColor: '#0277BD',
    sectionHeaderBg: '#E1F5FE',
    sectionHeaderText: '#01579B',
    bodyText: '#0a2540',
    decorativeClass: 'decor-summer',
  },
  backToSchool: {
    id: 'backToSchool',
    name: 'Back to School',
    emoji: '📚',
    primaryColor: '#1A237E',
    accentColor: '#F9A825',
    backgroundColor: '#F5F5FF',
    headerBg: 'linear-gradient(135deg, #1A237E 0%, #283593 100%)',
    headerText: '#F9A825',
    sectionBorderColor: '#1A237E',
    sectionHeaderBg: '#E8EAF6',
    sectionHeaderText: '#1A237E',
    bodyText: '#0d1440',
    decorativeClass: 'decor-backToSchool',
  },
}

export const SECTION_LABELS: Record<string, string> = {
  header: '📋 Header',
  presidentMessage: '💌 President\'s Message',
  todoList: '✅ To-Do List',
  birthdays: '🎂 Birthdays',
  birthAnnouncements: '👶 Birth Announcements',
  upcomingEvents: '📅 Upcoming Events',
  playgroups: '🧸 Playgroups',
  semesterDates: '🗓️ Semester Dates',
  clubSponsor: '⭐ Club Sponsor',
}
